[package]
name = "StillAliveReforged"
version = "0.1.0"
edition = "2021"
authors = ["Xanthus58 <xanthus58@protonmail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.15.0" 
color_please = "0.2.1"